
package com.utils.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceAnalysis", targetNamespace = "ws.utils.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceAnalysis {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "doAnalysisBpipUnit", targetNamespace = "ws.utils.com", className = "com.utils.ws.DoAnalysisBpipUnit")
    @ResponseWrapper(localName = "doAnalysisBpipUnitResponse", targetNamespace = "ws.utils.com", className = "com.utils.ws.DoAnalysisBpipUnitResponse")
    public void doAnalysisBpipUnit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "doAnalysisDoc", targetNamespace = "ws.utils.com", className = "com.utils.ws.DoAnalysisDoc")
    @ResponseWrapper(localName = "doAnalysisDocResponse", targetNamespace = "ws.utils.com", className = "com.utils.ws.DoAnalysisDocResponse")
    public void doAnalysisDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

}
