
package com.utils.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceAnalysisService", targetNamespace = "ws.utils.com", wsdlLocation = "http://localhost:8081/ws/syncAnalysis?wsdl")
public class WebServiceAnalysisService
    extends Service
{

    private final static URL WEBSERVICEANALYSISSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEANALYSISSERVICE_EXCEPTION;
    private final static QName WEBSERVICEANALYSISSERVICE_QNAME = new QName("ws.utils.com", "WebServiceAnalysisService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/syncAnalysis?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEANALYSISSERVICE_WSDL_LOCATION = url;
        WEBSERVICEANALYSISSERVICE_EXCEPTION = e;
    }

    public WebServiceAnalysisService() {
        super(__getWsdlLocation(), WEBSERVICEANALYSISSERVICE_QNAME);
    }

    public WebServiceAnalysisService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEANALYSISSERVICE_QNAME, features);
    }

    public WebServiceAnalysisService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEANALYSISSERVICE_QNAME);
    }

    public WebServiceAnalysisService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEANALYSISSERVICE_QNAME, features);
    }

    public WebServiceAnalysisService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceAnalysisService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceAnalysis
     */
    @WebEndpoint(name = "WebServiceAnalysisPort")
    public WebServiceAnalysis getWebServiceAnalysisPort() {
        return super.getPort(new QName("ws.utils.com", "WebServiceAnalysisPort"), WebServiceAnalysis.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceAnalysis
     */
    @WebEndpoint(name = "WebServiceAnalysisPort")
    public WebServiceAnalysis getWebServiceAnalysisPort(WebServiceFeature... features) {
        return super.getPort(new QName("ws.utils.com", "WebServiceAnalysisPort"), WebServiceAnalysis.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEANALYSISSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEANALYSISSERVICE_EXCEPTION;
        }
        return WEBSERVICEANALYSISSERVICE_WSDL_LOCATION;
    }

}
